import { Timestamp } from 'firebase/firestore';

import { TaskTackStatus } from '@shared/enums/enum';
import {
  User,
  Task,
  TaskTrack,
  Project,
  Vacation,
} from '@shared/interfaces/interfaces';

export const mockUsers: User[] = [
  {
    birthday: new Timestamp(900795600, 465000000),
    email: 'mivakhnenko@datamola.com',
    endDate: new Timestamp(1661050800, 882000000),
    fullName: 'Maria Ivakhnenko',
    id: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
    location: 'Minsk, Belarus',
    photo: 'https://avatars.githubusercontent.com/u/88663763?v=4',
    position: 'Administrator',
    qualification: 'Senior',
    role: 'admin',
    startDate: new Timestamp(1654030800, 882000000),
    timeZone: '+3',
  },
  {
    birthday: new Timestamp(751672800, 367000000),
    email: 'vchistiakov@datamola.com',
    endDate: new Timestamp(1664050800, 313000000),
    fullName: 'Vitalii Chistiakov',
    id: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
    location: 'Minsk, Belarus',
    photo:
      // eslint-disable-next-line max-len
      'https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/62970818a0eafd0069e86612/69cd9846-5c68-482e-bb26-81bf77da957b/128',
    position: 'Frontend Developer',
    qualification: 'middle',
    role: 'employee',
    startDate: new Timestamp(1664030800, 313000000),

    timeZone: '+3',
  },
  {
    birthday: new Timestamp(1025125200, 844000000),
    email: 'vkhodoruk@datamola.com',
    endDate: new Timestamp(1664050800, 283000000),
    fullName: 'Vladislav Khodoruk',
    id: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
    location: 'Minsk, Belarus',
    photo:
      // eslint-disable-next-line max-len
      'https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/6298604da0eafd0069e8f7cd/1656ba5b-b78b-4822-846f-ecb40c4e4899/128',
    position: 'Frontend Developer',
    qualification: 'Senior',
    role: 'employee',
    startDate: new Timestamp(1654030800, 283000000),

    timeZone: '+3',
  },
  {
    birthday: new Timestamp(802904400, 31000000),
    email: 'kborisenok@datamola.com',
    endDate: new Timestamp(1664050800, 517000000),
    fullName: 'Kirill Borisenok',
    id: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
    location: 'Bobruisk, Belarus',
    photo:
      // eslint-disable-next-line max-len
      'https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/629860aa1a2bdf007095b9bb/181bf52b-1854-4deb-a661-884a6a376802/128',
    position: 'CTO',
    qualification: 'Student',
    role: 'CTO',
    startDate: new Timestamp(1654030800, 517000000),
    timeZone: '+3',
  },
  {
    birthday: new Timestamp(867904915, 371000000),
    email: 'ashinkarev@datamola.com',
    endDate: new Timestamp(1661050800, 259000000),
    fullName: 'Andrei Shinkarev',
    id: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
    location: 'Mogilev, Belarus',
    photo:
      // eslint-disable-next-line max-len
      'https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/62985f0ac3dffc0068f5ddff/864cad92-da20-48f3-b5b4-54d2a6c74170/128',
    position: 'Project Manager',
    qualification: 'Student',
    role: 'manager',
    startDate: new Timestamp(1654030800, 259000000),

    timeZone: '+3',
  },
  {
    birthday: new Timestamp(773010000, 772000000),
    email: 'employee@google.com',
    endDate: new Timestamp(1661050800, 211000000),
    fullName: 'Elon Mask',
    id: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
    location: 'Minsk, Belarus',
    photo:
      'https://www.tadviser.ru/images/thumb/b/bc/Elon-SEC-HGK1DB.jpg/840px-Elon-SEC-HGK1DB.jpg',
    position: 'Frontend developer',
    qualification: 'Student',
    role: 'employee',
    startDate: new Timestamp(1654030800, 211000000),

    timeZone: '+3',
  },
];

export const mockTasks: Task[] = [
  {
    archived: false,
    id: '0N9SBvw8R48Ybb1rw3T4',
    name: 'Daily activity chart',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: '33vqSse9t7ZBt7L9dU4E',
    name: 'Create vacations  component',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: '3LWy9iNumYlcbj4XWIDA',
    name: 'Fix in progress style',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: '77DEZJONgyhBwwJT6uGC',
    name: 'Add vacations component',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: '7RSD0NbwupaS9X02TNZw',
    name: 'Working hours chart  component',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: '8K3meYpeXrGzpGjnJPnR',
    name: 'Today view (store)',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: '8NVvNqnhPXLdvtQOBaU9',
    name: 'Create activity by projects chart component',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'BZP4ofsoadm0UNgJSRk8',
    name: 'Fix bags in My Activity Page',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'DAbIvkXwQTpwc2fSTCyj',
    name: 'Projects page polishing',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'Dp62ch3RLoOnV2NMjky0',
    name: 'Integrate store',
    projectId: 'lrvIgoy3xaroJTWlBeTx',
  },
  {
    archived: true,
    id: 'EtmWicPcMobMNnSAsbRT',
    name: 'Create calendar navigation',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'FwXyPX0Ffi17hAmggPFA',
    name: 'Add time track form',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'Hc4YbEPzpiifROv5sa8O',
    name: 'Dachboard page polishing',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'I50QULVYHcH9nXhW1Acv',
    name: 'Add project page to CTO',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'MFBYTJqHVGoxtRWvsKj5',
    name: 'Study angular derectives',
    projectId: 'iyWKSkrUoKRMErqmbSUO',
  },
  {
    archived: false,
    id: 'QKjSwPFnjttXhANdb3ym',
    name: 'Create active tasks list  component',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: true,
    id: 'QY81kEvbTr0SbeUXnAgg',
    name: 'Add authorization',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'QaEZvVveoERACEtb4pFa',
    name: 'Change structure',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: true,
    id: 'TDIUIUOVf4jeIG9mAR3W',
    name: 'Integrate store',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'UWaVlIkICl5i9pAG7bk6',
    name: 'Activity total cards',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'Uo7r5QOnCaSxLBgdYk5X',
    name: 'Init',
    projectId: 'lrvIgoy3xaroJTWlBeTx',
  },
  {
    archived: false,
    id: 'VOEqF3fzuLwlWSpycFPQ',
    name: 'Paid vacation',
    projectId: 'kIjYlnhio4ghwoC0CyWf',
  },
  {
    archived: false,
    id: 'XgtweOoksn6fBDSE8i04',
    name: 'Create today wiew component',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'biTabiSBOm6oIEgtTeXb',
    name: 'Create project team',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'dPnRTrV2RwY159uYYqCV',
    name: 'Add report page to manager ',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: true,
    id: 'f0gIlkC9lXqjC8gWcYV3',
    name: 'Add Angular Material',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'gE62UaYK4O1ANmriuPrV',
    name: 'My Activity page polishing',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'gJGIgdv9AagjEnE3ZD2u',
    name: 'Create database',
    projectId: 'DAK4rhvLhUoROKPuKMIz',
  },
  {
    archived: true,
    id: 'gkHHSsV3n1eKiqqDZe27',
    name: 'create Team page',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: true,
    id: 'hn5F9D4QrvTMmFK7sxmB',
    name: 'Projects list with search',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'hzARzr0nxoNf23K9hGv8',
    name: 'Create efficiency component',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'kn6pTtLFGEoYzGuRWYem',
    name: 'Create chart',
    projectId: 'BoavfTxFkFinfWUa8lLd',
  },
  {
    archived: false,
    id: 'kov4FQZtONPwStzhh3sd',
    name: 'Study NgRx library',
    projectId: 'iyWKSkrUoKRMErqmbSUO',
  },
  {
    archived: false,
    id: 'loY95YR5iaDUjAVa3F1M',
    name: 'Project tasks list',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'nIdOJJGELs0LYbqMWneX',
    name: 'Add report page to admin',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'ncOjp57681m3ze28AUC5',
    name: 'Unpaid vacation',
    projectId: 'kIjYlnhio4ghwoC0CyWf',
  },
  {
    archived: false,
    id: 'ns3AEnKBPZba136yvRlX',
    name: 'My report page polishing',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'pr0QyzdmBmfo2gIdkQ0l',
    name: 'Create profile page',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'qrrUL82KfjnzFWEIToEH',
    name: 'Create Projects Page',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'rWXe8JE1LkXx1BlpGYuj',
    name: 'Study information about angular pipe',
    projectId: 'iyWKSkrUoKRMErqmbSUO',
  },
  {
    archived: false,
    id: 'uwafS8S0a3tgMKBKzzaR',
    name: 'Study angular dependency injection',
    projectId: 'iyWKSkrUoKRMErqmbSUO',
  },
  {
    archived: false,
    id: 'v0LbADWIFPqFSKM6EuMr',
    name: 'Daily activity chart(store->chart)',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'wHxfe2rjYdfm6maaVAO7',
    name: 'Study RxJs',
    projectId: 'iyWKSkrUoKRMErqmbSUO',
  },
  {
    archived: true,
    id: 'wwwKItkbi4XLCeph58X6',
    name: 'Calendar week view',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'xBgaMXjSCTN8snri41dW',
    name: 'Create project tasks list',
    projectId: 'pdCsdrXhodWnZieCfp6O',
  },
  {
    archived: false,
    id: 'xy030Twv5XBYxSfdiH1W',
    name: 'Sick leave',
    projectId: 'kIjYlnhio4ghwoC0CyWf',
  },
];

export const mockTaskTracks: TaskTrack[] = [
  {
    comments: 'awdwa',
    date: new Timestamp(1659733200, 0),
    duration: 1,
    id: '0u2GoiywERPbjxKp9iqn',
    overtime: false,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments: '',
    date: new Timestamp(1659301200, 0),
    duration: 1,
    id: '0vifnpAy08k9EMvZ4V29',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'BoavfTxFkFinfWUa8lLd',
    status: '',
    taskId: 'kn6pTtLFGEoYzGuRWYem',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1659733200, 0),
    duration: 1,
    id: '18bIWvAp91oIsuREKgc4',
    overtime: true,
    overtimeDuration: 0.5,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Задача в ckickup https://app.clickup.com/t/2kwx0ckLink to git repo https://bitbucket.org/AMC_TV/team-1/pull-requests/121',
    date: new Timestamp(1659301200, 0),
    duration: 3,
    id: '1kWghtbRFQ57SQqNiTdy',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'I50QULVYHcH9nXhW1Acv',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659906000, 0),
    duration: 1,
    id: '2HEMMHaw3o99sfjNsMO8',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      "Fix style 'in progress' element in dashboard. Task in clickup https://app.clickup.com/t/2ngfp1k Link to get repo https://bitbucket.org/AMC_TV/team-1/pull-requests/118",
    date: new Timestamp(1659387600, 0),
    duration: 3,
    id: '2wafSpymxlogQUKleQ6W',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '3LWy9iNumYlcbj4XWIDA',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659474000, 0),
    duration: 4,
    id: '2z7THkXe6pslCCLYf20L',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: null,
    date: new Timestamp(1659560400, 0),
    duration: 1,
    id: '3NcBE3ZIrr3Oh374Y9fH',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'MFBYTJqHVGoxtRWvsKj5',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments:
      'Study info about store in angular.Source https://ngrx.io/guide/store.',
    date: new Timestamp(1659942716, 0),
    duration: 1,
    id: '4OO78DmB3VJPRnlHCB76',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'kov4FQZtONPwStzhh3sd',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Beatae enim repudiandae quis delectus possimus veniam iure eum iste consequuntur.https://www.google.com/ Lorem ipsum dolor sit amet consectetur, adipisicing elit.',
    date: new Timestamp(1659474000, 0),
    duration: 1,
    id: '4bgvjncJ9juZdExvsTmW',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments: 'create hours chart view',
    date: new Timestamp(1659474000, 0),
    duration: 5,
    id: '5WqoZrkjjh9nHCgoP83p',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: 'done',
    taskId: '7RSD0NbwupaS9X02TNZw',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
  },
  {
    comments: '',
    date: new Timestamp(1659906000, 0),
    duration: 2,
    id: '75zNvfbbBXXrto8uAezi',
    overtime: true,
    overtimeDuration: 0.5,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments: '',
    date: new Timestamp(1659301200, 0),
    duration: 1,
    id: '7Sgv3FRUAJKHNaPDvvO6',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '33vqSse9t7ZBt7L9dU4E',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Ссылка на задачу в Clickup https://app.clickup.com/t/2kwx0ck Link to git repo https://bitbucket.org/AMC_TV/team-1/pull-requests/121',
    date: new Timestamp(1659301200, 0),
    duration: 3,
    id: '7UczEhP3fRXP5eJr6pJL',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'nIdOJJGELs0LYbqMWneX',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659301200, 0),
    duration: 1,
    id: '83Qv4UnHd6ZW4TL5NvGh',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'BoavfTxFkFinfWUa8lLd',
    status: '',
    taskId: 'kn6pTtLFGEoYzGuRWYem',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments: '',
    date: new Timestamp(1658091600, 0),
    duration: 2,
    id: '96EIUKidaB6vHHBqq8RN',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1659560400, 0),
    duration: 4,
    id: 'BvbOdkaBS6gwmkT1EJq2',
    overtime: true,
    overtimeDuration: 3,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1657486800, 0),
    duration: 2,
    id: 'EDcVJRAcvMIM5qt9feQh',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: 'dsdfdsf',
    date: new Timestamp(1657227600, 0),
    duration: 4,
    id: 'Fet7gIKI537tVEPJjsxh',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'xBgaMXjSCTN8snri41dW',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments:
      'Study info about store in angular.Source https://ngrx.io/guide/store.',
    date: new Timestamp(1659560400, 0),
    duration: 1,
    id: 'G8A6GNItcP468uCbjQ33',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'kov4FQZtONPwStzhh3sd',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: null,
    date: new Timestamp(1659733200, 0),
    duration: 7,
    id: 'GYpAPayy7oTUrc8fOEbv',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'kov4FQZtONPwStzhh3sd',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: null,
    date: new Timestamp(1659906000, 0),
    duration: 5,
    id: 'HUZTQn0YuIa4lLwkqStH',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: 'done',
    taskId: 'QKjSwPFnjttXhANdb3ym',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Add vacations in firebase. Merged base and component. Task in clickup https://app.clickup.com/t/2gakq5b.Link to git https://bitbucket.org/AMC_TV/team-1/pull-requests/135.',
    date: new Timestamp(1659942716, 0),
    duration: 4,
    id: 'HnjkjBEydS86kcrus2bI',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '77DEZJONgyhBwwJT6uGC',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Integrate store selectors in profile component and creat functions which help convert information. Mix vacations and holiday data in vacations component. ',
    date: new Timestamp(1659646800, 0),
    duration: 2,
    id: 'K77354klRpIT4bTAkQtY',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'Dp62ch3RLoOnV2NMjky0',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659906000, 0),
    duration: 2,
    id: 'L5fypev11SJa59IikFuw',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'xBgaMXjSCTN8snri41dW',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa iste adipisci facilis perspiciatis quam voluptatum, ipsum asperiores quo, dolor at atque cupiditate, aliquam possimus sapiente impedit placeat! Rerum, voluptatem autem.',
    date: new Timestamp(1657314000, 0),
    duration: 3,
    id: 'LrOC5q7u1DJFkaHK72LX',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: 'in progress',
    taskId: 'xBgaMXjSCTN8snri41dW',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments: null,
    date: new Timestamp(1659819600, 0),
    duration: 8,
    id: 'M1p7TGQjkwKsToODEZzM',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'uwafS8S0a3tgMKBKzzaR',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1657486800, 0),
    duration: 3,
    id: 'MZi0MOIwZA6wKJRufNVF',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1659474000, 0),
    duration: 1,
    id: 'NYyNi0eBHg9AYDE7hfck',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '7RSD0NbwupaS9X02TNZw',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments:
      'Change the structure of folders for renderers depending on authorization.',
    date: new Timestamp(1659560400, 0),
    duration: 2,
    id: 'O7kDGsp2Odg2sHf36Ut5',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'QaEZvVveoERACEtb4pFa',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659387600, 0),
    duration: 3,
    id: 'PQqWfzSO6Is13H1xDaT1',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
  },
  {
    comments: '',
    date: new Timestamp(1659301200, 0),
    duration: 1,
    id: 'QJFNAiqw1ktclQJBrLRV',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'v0LbADWIFPqFSKM6EuMr',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
  },
  {
    comments: '',
    date: new Timestamp(1659301200, 0),
    duration: 2,
    id: 'QauvNllPX41gNBC3sxOR',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '33vqSse9t7ZBt7L9dU4E',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
  },
  {
    comments: '',
    date: new Timestamp(1659906000, 0),
    duration: 1,
    id: 'ShD2P1UCRLTmjqFSm6XI',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '33vqSse9t7ZBt7L9dU4E',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments: null,
    date: new Timestamp(1659560400, 0),
    duration: 3,
    id: 'So32ExhwyWLxUdsaOtxn',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '33vqSse9t7ZBt7L9dU4E',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Add vacations in firebase. Merged base and component. Task in clickup https://app.clickup.com/t/2gakq5b.Link to git https://bitbucket.org/AMC_TV/team-1/pull-requests/135.',
    date: new Timestamp(1659646800, 0),
    duration: 4,
    id: 'T1N7cBGQd5vI7bacYrqJ',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '77DEZJONgyhBwwJT6uGC',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: 'http://www.google.com/',
    date: new Timestamp(1659474000, 0),
    duration: 1,
    id: 'T1X49osg48Q27vVHiboL',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments: '',
    date: new Timestamp(1659733200, 0),
    duration: 1,
    id: 'TEwROiBugXy234dbu8pY',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'vvvvvvvvvvvvvvvvvvvvvv vvvvvvvvvvvvvvvvvv vvvvvvvvvvvvvvvvvvvvvvvvv vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv vvvvvvvvvvvvvvvvvvvvvvvvvvv',
    date: new Timestamp(1657314000, 0),
    duration: 2,
    id: 'TF0LuEOYapFhYkzmGnAK',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: 'in progress',
    taskId: 'xBgaMXjSCTN8snri41dW',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments: 'https://www.google.com/',
    date: new Timestamp(1659474000, 0),
    duration: 1,
    id: 'TJBl3FpFrzSpFta5tKoX',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: 'in progress',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments: '',
    date: new Timestamp(1659301200, 0),
    duration: 8,
    id: 'UsjbTOPCzbDb4McTnxFL',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'UWaVlIkICl5i9pAG7bk6',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1659474000, 0),
    duration: 1,
    id: 'VAIPg7tQjPEs3sFZyVJE',
    overtime: true,
    overtimeDuration: 1,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments: '',
    date: new Timestamp(1658712903, 0),
    duration: 6,
    id: 'VUW0ERxrxYJlQcU3IhQ7',
    overtime: true,
    overtimeDuration: 10,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: 'in progress',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: 'https://google.com/',
    date: new Timestamp(1659474000, 0),
    duration: 1,
    id: 'VzcCHi65h6VgSXl8XllL',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments:
      'Study info about store in angular.Source https://ngrx.io/guide/store.',
    date: new Timestamp(1659646800, 0),
    duration: 1,
    id: 'WfLEQas6cOoZu6pE3DSk',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'kov4FQZtONPwStzhh3sd',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit.Atque, quos. Enim aperiam inventore accusamus ipsa voluptate, error nihil voluptates. Beatae enim repudiandae quis delectus possimus veniam iure eum iste consequuntur. https://google.com/ Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque, quos. Enim aperiam inventore accusamus ipsa voluptate, error nihil voluptates. Beatae enim repudiandae quis delectus possimus veniam iure eum iste consequuntur. http://www.google.com/ Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque, quos. http://google.com/ Enim aperiam inventore accusamus ipsa voluptate, error nihil voluptates. Beatae enim repudiandae quis delectus possimus veniam iure eum iste consequuntur. https://google1.com',
    date: new Timestamp(1659474000, 0),
    duration: 1,
    id: 'WmsHVZkG1tsBjgLoi0Tm',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments: '',
    date: new Timestamp(1659301200, 0),
    duration: 1,
    id: 'X4E9CIqQeSVHPSzJpEPm',
    overtime: true,
    overtimeDuration: 0.5,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '33vqSse9t7ZBt7L9dU4E',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
  },
  {
    comments: '',
    date: new Timestamp(1659387600, 0),
    duration: 3,
    id: 'XXb8PFgzZpijzsIdZzrv',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '33vqSse9t7ZBt7L9dU4E',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Integrate store selectors in profile component and creat functions which help convert information. Mix vacations and holiday data in vacations component. ',
    date: new Timestamp(1659942716, 0),
    duration: 2,
    id: 'YImkPuPVbWN1S6KlWgJb',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'Dp62ch3RLoOnV2NMjky0',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659560400, 0),
    duration: 4,
    id: 'YcKaNL4e3PZ6EUPOWyen',
    overtime: true,
    overtimeDuration: 1,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: 'in progress',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments: null,
    date: new Timestamp(1659646800, 0),
    duration: 8,
    id: 'Zz1Az185GUau2WSN6h1L',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1657400400, 0),
    duration: 3,
    id: 'aUYyRWCp155mdRx6bZgp',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: 'in progress',
    taskId: 'xBgaMXjSCTN8snri41dW',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments: '',
    date: new Timestamp(1657535499, 0),
    duration: 3,
    id: 'dBhXfrNBVNovZqE8Zc9B',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '33vqSse9t7ZBt7L9dU4E',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Create efficiency component in My Activity page. Task in clickup https://app.clickup.com/t/2hjmyp4 Link to git repo https://bitbucket.org/AMC_TV/team-1/pull-requests/114.',
    date: new Timestamp(1659474000, 0),
    duration: 3,
    id: 'dtvy8mkAyKUL05EDcp2T',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'hzARzr0nxoNf23K9hGv8',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659906000, 0),
    duration: 1,
    id: 'dwXxfo2p81Bi35PH8ThC',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'BoavfTxFkFinfWUa8lLd',
    status: '',
    taskId: 'kn6pTtLFGEoYzGuRWYem',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments: '',
    date: new Timestamp(1659474000, 0),
    duration: 1,
    id: 'eYxwAozg4iCp1KW3sOL5',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '7RSD0NbwupaS9X02TNZw',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments: '222222',
    date: new Timestamp(1659387600, 0),
    duration: 6,
    id: 'fHa4ZeXhVjoQrxj6yFt3',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'wwwKItkbi4XLCeph58X6',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Fix broken activity chart component. Task in clickup https://app.clickup.com/t/2gakrjt Link to git repo https://bitbucket.org/AMC_TV/team-1/pull-requests/97',
    date: new Timestamp(1659560400, 0),
    duration: 1,
    id: 'fn3JOuNSAAglaD6g3TCL',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'gE62UaYK4O1ANmriuPrV',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659646800, 0),
    duration: 9,
    id: 'g57yeFvRvoL9DcgiikGw',
    overtime: true,
    overtimeDuration: 3,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'Dp62ch3RLoOnV2NMjky0',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments:
      'Study RxJs library. Practical use. Source https://rxjs.dev/guide/overview',
    date: new Timestamp(1659474000, 0),
    duration: 2,
    id: 'gMLIDUwE8kCgM5p63n6x',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'wHxfe2rjYdfm6maaVAO7',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: null,
    date: new Timestamp(1659474000, 0),
    duration: 5,
    id: 'jBX7ebRQKIZ7L38LRGJa',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'QKjSwPFnjttXhANdb3ym',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments: '',
    date: new Timestamp(1659646800, 0),
    duration: 3,
    id: 'kI9hYAbtnqWGFK17pPkQ',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'lrvIgoy3xaroJTWlBeTx',
    status: '',
    taskId: 'Uo7r5QOnCaSxLBgdYk5X',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments: '',
    date: new Timestamp(1659474000, 0),
    duration: 2,
    id: 'lDC6kQziH5nUb7YY1jDS',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'BoavfTxFkFinfWUa8lLd',
    status: '',
    taskId: 'kn6pTtLFGEoYzGuRWYem',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments:
      // eslint-disable-next-line max-len
      'Task in clickup https://app.clickup.com/t/2gakrjt Lint to git repo https://bitbucket.org/AMC_TV/team-1/pull-requests/87',
    date: new Timestamp(1659474000, 0),
    duration: 2,
    id: 'mABz1eEO6zSYTenI6Zvr',
    overtime: true,
    overtimeDuration: 1,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'BZP4ofsoadm0UNgJSRk8',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: null,
    date: new Timestamp(1659301200, 0),
    duration: 7,
    id: 'mKcBeOsSyvUi88Hpojnw',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments:
      'Source https://angular.io/api/core/Directive and https://metanit.com/web/angular2/3.2.php',
    date: new Timestamp(1659387600, 0),
    duration: 2,
    id: 'manoJtlisY0MOzGhVnvD',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'MFBYTJqHVGoxtRWvsKj5',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments:
      'Вид на страницу https://develop.auroravts.com/lavds45jlmhi1pgafg6v6lc8e5mwajnr/report',
    date: new Timestamp(1659387600, 0),
    duration: 2,
    id: 'n23XMrt9Qk6LXpeGj6oO',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'dPnRTrV2RwY159uYYqCV',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659387600, 0),
    duration: 4,
    id: 'nRy8Og4Y3aVVcmi6V9GX',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1659560400, 0),
    duration: 1,
    id: 'nWM5mwT39MWKutpmIGLA',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '7RSD0NbwupaS9X02TNZw',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
  },
  {
    comments: '',
    date: new Timestamp(1659387600, 0),
    duration: 4,
    id: 'oCNks6PvbgnUBe91WNqj',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '8K3meYpeXrGzpGjnJPnR',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments: '',
    date: new Timestamp(1659992400, 0),
    duration: 5,
    id: 'qDcP6KFBTwDNS95tnwub',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: 'in progress',
    taskId: '0N9SBvw8R48Ybb1rw3T4',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1659906000, 0),
    duration: 4,
    id: 'r61DdrKbdGCCFkvVcIYq',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    date: new Timestamp(1659819600, 0),
    duration: 1,
    id: 'rWxs1dHSAVPM1clPryTO',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'rWXe8JE1LkXx1BlpGYuj',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments: '',
    date: new Timestamp(1659301200, 0),
    duration: 1,
    id: 'rZDrr6VNjH9uleKQ4sU1',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '7RSD0NbwupaS9X02TNZw',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: '',
    date: new Timestamp(1659906000, 0),
    duration: 1,
    id: 'rgg8L56RMA7KSSzYoEYa',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments: '',
    date: new Timestamp(1657535499, 0),
    duration: 1,
    id: 'rzII60XeOjedTldViiUo',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    comments: '',
    date: new Timestamp(1658990476, 0),
    duration: 1,
    id: 'sQEgQpv0l3nvshNycxad',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'XgtweOoksn6fBDSE8i04',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
  },
  {
    comments: null,
    date: new Timestamp(1659560400, 0),
    duration: 4,
    id: 'sntqpGyOZTSw5GXvj4Pa',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'BoavfTxFkFinfWUa8lLd',
    status: '',
    taskId: 'kn6pTtLFGEoYzGuRWYem',
    taskTrackStatus: TaskTackStatus.Sended,
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    comments: null,
    date: new Timestamp(1659733200, 0),
    duration: 4,
    id: 'tTldFlzYTRYoBYWWIu3q',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'f0gIlkC9lXqjC8gWcYV3',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    comments: '',
    date: new Timestamp(1659387600, 0),
    duration: 5,
    id: 'tjHcRXaHFnDWiiBvYIqk',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'DAK4rhvLhUoROKPuKMIz',
    status: '',
    taskId: 'gJGIgdv9AagjEnE3ZD2u',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments: '',
    date: new Timestamp(1659474000, 0),
    duration: 3,
    id: 'ukeW321Lh0lldXiVOTdm',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: '7RSD0NbwupaS9X02TNZw',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments: '',
    date: new Timestamp(1659906000, 0),
    duration: 2,
    id: 'uuMBIRANtIp0T9ea87Yt',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'BoavfTxFkFinfWUa8lLd',
    status: '',
    taskId: 'kn6pTtLFGEoYzGuRWYem',
    taskTrackStatus: TaskTackStatus.New,
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    comments:
      'Source https://angular.io/api/core/Pipe and https://metanit.com/web/angular2/8.1.php. Simulation pipes work.',
    date: new Timestamp(1659942716, 0),
    duration: 1,
    id: 'w0oS9D0Z3UhXaIf0VNF3',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'rWXe8JE1LkXx1BlpGYuj',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments:
      'Source https://metanit.com/web/angular2/4.1.php and https://angular.io/guide/dependency-injection',
    date: new Timestamp(1659301200, 0),
    duration: 2,
    id: 'w9Py4t18kkUoCLOB12ch',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'uwafS8S0a3tgMKBKzzaR',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments: '',
    date: new Timestamp(1659992400, 0),
    duration: 2,
    id: 'zHptHOMn4QMWPNg3xh59',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'pdCsdrXhodWnZieCfp6O',
    status: '',
    taskId: 'BZP4ofsoadm0UNgJSRk8',
    taskTrackStatus: TaskTackStatus.New,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    comments:
      'Source https://angular.io/api/core/Pipe and https://metanit.com/web/angular2/8.1.php. Simulation pipes work.',
    date: new Timestamp(1659646800, 0),
    duration: 1,
    id: 'ztwrIQSyiKjGH0j4s1v3',
    overtime: false,
    overtimeDuration: 0,
    projectId: 'iyWKSkrUoKRMErqmbSUO',
    status: '',
    taskId: 'rWXe8JE1LkXx1BlpGYuj',
    taskTrackStatus: TaskTackStatus.Approved,
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
];

export const mockProjects: Project[] = [
  {
    color: '#F8CF45',
    description:
      'From Data To Insights. Smart tool and fast GPU data processing.',
    fullName: 'dataMill',
    id: 'BoavfTxFkFinfWUa8lLd',
    managersId: [
      'mocfzWIHXuYiYbefQMTclEotJr83',
      'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
      'baepq7VLWRVK2XcOQkMHyZlfd6I2',
    ],
    name: 'dataMill',
    tasksId: [],
  },
  {
    color: '#9174E2',
    description:
      'All activities related to site updates, such as new courses announcements and open positions.',
    fullName: 'DataMola official site',
    id: 'DAK4rhvLhUoROKPuKMIz',
    managersId: [
      'mocfzWIHXuYiYbefQMTclEotJr83',
      'baepq7VLWRVK2XcOQkMHyZlfd6I2',
    ],
    name: 'datamola.com',
    tasksId: [],
  },
  {
    color: '#F8CF45',
    description: 'Education during Angular Course 2022.',
    fullName: 'Angular Course',
    id: 'iyWKSkrUoKRMErqmbSUO',
    managersId: [
      'mocfzWIHXuYiYbefQMTclEotJr83',
      'baepq7VLWRVK2XcOQkMHyZlfd6I2',
    ],
    name: 'Education',
    tasksId: [
      'MFBYTJqHVGoxtRWvsKj5',
      'uwafS8S0a3tgMKBKzzaR',
      'wHxfe2rjYdfm6maaVAO7',
      'kov4FQZtONPwStzhh3sd',
      'rWXe8JE1LkXx1BlpGYuj',
    ],
  },
  {
    color: '#CD59B1',
    description: 'Application for tracking work hours and managing projects.',
    fullName: 'TrackMola application',
    id: 'pdCsdrXhodWnZieCfp6O',
    managersId: [
      'mocfzWIHXuYiYbefQMTclEotJr83',
      'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
      'baepq7VLWRVK2XcOQkMHyZlfd6I2',
    ],
    name: 'TrackMola',
    tasksId: [
      '0N9SBvw8R48Ybb1rw3T4',
      '33vqSse9t7ZBt7L9dU4E',
      '7RSD0NbwupaS9X02TNZw',
      '8K3meYpeXrGzpGjnJPnR',
      '8NVvNqnhPXLdvtQOBaU9',
      'DAbIvkXwQTpwc2fSTCyj',
      'EtmWicPcMobMNnSAsbRT',
      'FwXyPX0Ffi17hAmggPFA',
      'Hc4YbEPzpiifROv5sa8O',
      'QKjSwPFnjttXhANdb3ym',
      'QY81kEvbTr0SbeUXnAgg',
      'TDIUIUOVf4jeIG9mAR3W',
      'UWaVlIkICl5i9pAG7bk6',
      'XgtweOoksn6fBDSE8i04',
      'biTabiSBOm6oIEgtTeXb',
      'f0gIlkC9lXqjC8gWcYV3',
      'gE62UaYK4O1ANmriuPrV',
      'gkHHSsV3n1eKiqqDZe27',
      'hn5F9D4QrvTMmFK7sxmB',
      'ns3AEnKBPZba136yvRlX',
      'pr0QyzdmBmfo2gIdkQ0l',
      'qrrUL82KfjnzFWEIToEH',
      'v0LbADWIFPqFSKM6EuMr',
      'wwwKItkbi4XLCeph58X6',
      'xBgaMXjSCTN8snri41dW',
      'jxO5Sd5l9PHnifQyKun8',
      'nIdOJJGELs0LYbqMWneX',
      '3LWy9iNumYlcbj4XWIDA',
      '77DEZJONgyhBwwJT6uGC',
      'hzARzr0nxoNf23K9hGv8',
      'BZP4ofsoadm0UNgJSRk8',
      'QaEZvVveoERACEtb4pFa',
    ],
  },
];

export const mockVacations: Vacation[] = [
  {
    color: '#F4914A',
    comment: 'ывыфв',
    periodEnd: new Timestamp(1660165199, 0),
    periodStart: new Timestamp(1660078800, 0),
    type: 'unpaid',
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
  {
    color: '#F4BF4A',
    comment: 'чЫвыф',
    periodEnd: new Timestamp(1660251599, 0),
    periodStart: new Timestamp(1660165200, 0),
    type: 'paid',
    userId: 'FyTQtfAXBMPaa3yKJ4TmVVgTA872',
  },
  {
    color: '#f4bf4a',
    comment: '',
    periodEnd: new Timestamp(1660683599, 0),
    periodStart: new Timestamp(1660597200, 0),
    type: 'paid',
    userId: 'oJsHMaprEsZBeyYaAfS8xoR9RP02',
  },
  {
    color: '#F4914A',
    comment: '',
    periodEnd: new Timestamp(1660856399, 0),
    periodStart: new Timestamp(1660424400, 0),
    type: 'unpaid',
    userId: 'P4SeopCIcgbAmGkoS8JE0Rq0t1v1',
  },
  {
    color: '#F4CF4A',
    comment: '',
    periodEnd: new Timestamp(1661201999, 0),
    periodStart: new Timestamp(1661115600, 0),
    type: 'other',
    userId: 'Y2nsuR3ejZMJxvxHnVZ1hjQlbV32',
  },
  {
    color: '#F4914A',
    comment: '',
    periodEnd: new Timestamp(1660856399, 0),
    periodStart: new Timestamp(1660165200, 0),
    type: 'paid',
    userId: 'ZI4fLQuaHfduoEdxAj7YevkrSq62',
  },
  {
    color: '#95CE7A',
    comment: '',
    periodEnd: new Timestamp(1661461199, 0),
    periodStart: new Timestamp(1661374800, 0),
    type: 'sick',
    userId: 'baepq7VLWRVK2XcOQkMHyZlfd6I2',
  },
];
